- README.md
The current example URLs come from the source tree of the `new_plugin`
repo, implying that those binaries are checked into the repo itself.
This commit updates the example to provide GitHub release URLs for those
binaries instead, at the version number specified in the plugin example,
and over HTTPS.
> README: use secure GitHub release URLs in binaries example

- repo-index.yml
Currently fails with:
```
$ cf install-plugin 'CF App Stack Changer' -r 'CF-Community'
Looking up 'CF App Stack Changer' from repository 'CF-Community'
FAILED
Download attempt failed: Error downloading file from https://github.com/simonleung8/cli-stack-changer/raw/master/bin/win64/cli-stack-changer_windows_amd64
Unable to install, plugin is not available from the given url.
```
> Fixing missing .exe file extension for cli-stack-changer on win64

- repo-index.yml
This updates the repo listing for the Diego-SSH plugin to version 0.1.2.
> Update Diego-SSH plugin listing to version 0.1.2

- repo-index.yml
Release v1.1.0 of Targets plugin with the following fixes:
- ```cf set-target -f``` no longer overwrites the previously set target with current values
- ```cf set-target``` to an unknown target gives a friendlier error message
> Update to latest release of Targets plugin

- repo-index.yml
Convenience plugin to provide access to https://github.com/krujos/willitconnect
Current version supports using proxies as well as setting a non-default route for the willitconnect application
> plugins: add willitconnect

- repo-index.yml
This is an update to the firehose nozzle plugin:
- Fix building with latest cf cli
- Bump all other dependencies in order to get envelope tag support
- Upgrade NOAA consumer
> Update the firehose nozzle plugin

- repo-index.yml
I've had to fix a bug in the plugin due to the CLI API changes.
> Update CopyEnv to 1.1.1

- repo-index.yml
Please add `update-cli` plugin (https://github.com/tcnksm/cf-plugin-update-cli)
It checks cloudfoundry/cli update and downloads if current installed version is not latest.  
We use it inside Rakuten for a while and works well. So we want to provide it to the community, too.
> Add update-cli plugin

- repo-index.yml
https://github.com/18F/cf-route-lookup/releases/tag/v1.1.0
> upgrade route-lookup plugin to v1.1.0

- repo-index.yml
`cf nozzle` and `cf app-nozzle` no longer filters envelopes of type `HttpStart` and `HttpStop` because they are not supported by Loggregator any more.
> bumps firehose plugin to 0.12.0

- repo-index.yml
Updated the plugin repo index to reference the latest release of the copy plugin.
> updated to latest release (0.9.4) of `copy` plugin

- repo-index.yml
This adds the CF Networking plugin v1.2.0
We have [added tooling to our CI repo](https://github.com/cloudfoundry-incubator/cf-networking-ci/commit/b9e00660ce59dd71c34544a96fb0a38e6882cb3d) to automatically generate these pull requests in the future. This tooling uses `bosh interpolate` to update the yml file, which orders all the keys within a hash alphabetically.
We discussed this briefly [here](https://cloudfoundry.slack.com/archives/C032824SM/p1499725300988109), but there was some misunderstanding about what is alphabetized.  Hopefully this makes it more clear and future commits will look less messy.
/cc @chinangela
> Update CF Networking plugin

- repo-index.yml
- Fixes a minor bug
- Adds `-raw` flag to metadata for better usage output.
> Updates AppMetrics plugin to v1.0.1

- repo-index.yml
Add conduit to the repo index so Cloud Foundry users can install the plugin easily from the main Cloud Foundry CLI plugin repository.
Code check
> Add new CLI plugin: conduit to the repo

- repo-index.yml
Version 2.0.0 aligns the name of the plugin with the name of the command it contributes to the CLI. Thus, the plugin name changes from `JavaPlugin` to `java`.
To prevent backwards incompatibilities over the update, the identifier of the plugin in the repository is also changed in the repo from `java-plugin` to `java`.
> Update the Java plugin to version 2.0.0

- repo-index.yml
Added CF Dev plugin to the cli-plugin-repo.  We currently only support a macOS version of the plugin, but plan to add Windows and Linux versions in the near future.
> Added CF Dev plugin

- repo-index.yml
Updated to the checksum values for the latest downloadable binaries. Re-added the plugin following the earlier deletion. Replaced the download URI with versioned paths.
> Updating CopyEnv checksum values and re-adding CopyEnv to repo-index.yml

- repo-index.yml
New version of CF Dev - v 0.0.8 - addresses lack of support for -c and -m flag in windows version
> Fixed windows cli verison flags

- repo-index.yml
- the core cli now has the network-policy functionality
[#160364892]
Signed-off-by: Christian Ang <cang@pivotal.io>
> remove reference to deprecated networking plugin

- repo-index.yml
Signed-off-by: Peter Stone <pstone@pivotal.io>
This plugin allows users to register metric sources for emission into the loggregator system.
They can currently register metrics endpoints in prometheus exposition format or structured logs in either DogStatsD or JSON format.
> add metric-registrar plugin

- repo-index.yml
Adds ssh keepalive to prevent idle connections timing out.
> Update conduit plugin to 0.0.6

- ui/css/cff.css
- ui/index.html
Show para icon when hovering over header, in the same manner as
godoc.org does.
> Make plugin names anchors so that individual plugins can be linked to

- repo-index.yml
New plugin based on autopilot (fork).
Rename newest version to the plugin to cf-puppeteer because of issue
[#282](https://github.com/cloudfoundry/cli-plugin-repo/pull/282#issuecomment-463328661)
> [NEW] cf-puppeteer plugin for zero-downtime-deployment

- repo-index.yml
The app created by conduit now has a random name, derived from the current unix timestamp, rather than the PID of the process.
> Update conduit plugin to 0.0.7

- repo-index.yml
I implemented a cf plugin to push with vault.
[hashicorp/vault: A tool for secrets management, encryption as a service, and privileged access management](https://github.com/hashicorp/vault)
This plugin allows evaluating parameter in the manifest with the vault.
> add push-with-vault plugin

- repo-index.yml
Updates route weight plugin to include fixes from https://github.com/tstannard/set-weights-plugin/releases/tag/1.1.0
Signed-off-by: Alex Standke <astandke@pivotal.io>
> update route weight plugin

- repo-index.yml
Adding a new plugin, cf-rolling-restart, to the community repo. Helps perform zero downtime restarts on PCF applications.
> Add cf-rolling-restart v1.1.1 to Community Plugins

- repo-index.yml
This PR updates conduit to our latest release which enable the use of SHA256 encrypted keys.
> Bump conduit to v0.0.8

- repo-index.yml
Signed-off-by: Melena Suliteanu <msuliteanu@pivotal.io>
N/A
This PR updates the version of the cf-drain-cli to v2.0.0. This version removes the v2-drain-space, v2-migrate-space-drain, …
> Update cf drain cli to v2.0.0

- repo-index.yml
We updated the target url for `metric-registrar-cli` to point to the latest version.
Users of the cli will get the latest version by default.
Moderate. Installing the version currently targeted causes a bug. Updating to the latest version will fix the issue.
> Update version of metric-registrar-cli to latest [#169954901]

- repo-index.yml
Update CF-Puppeteer to new Version 1.2.0
Some new features are implemented (--vars-file option was back)
Fix some bugs while using the legacy option (--legacy-push)
The rest explained in the Blog and the Changelog file.
Kind Regards
> UPDATE CF-Puppeteer Version to 1.2.0

- repo-index.yml
Previously, `cf conduit` would exit 0 regardless of the exit status of the child process
Now `cf conduit` exits with the exit status of the child process
Users can now error check using the exit code (i.e. `$?`) instead of parsing output, this makes `cf conduit` more valuable in automated pipelines (e.g. `cf conduit my-db -- pgdump`)
https://github.com/alphagov/paas-cf-conduit/issues/44
https://github.com/alphagov/paas-cf-conduit/pull/45
Our users want this in the official repo so they do not have to install from source
Anyone who uses `cf conduit`
> Update cf conduit to v0.0.10

- repo-index.yml
Update `conduit` plugin to v0.0.11
See [release notes](https://github.com/alphagov/paas-cf-conduit/releases/tag/v0.0.11)
Pre-flight check prevent hard to debug issues
More context when using the `--verbose`flag to debug keepalive failures
Quality of life
Any user of `conduit`
> Update conduit to v0.0.11

- repo-index.yml
[#174235339](https://www.pivotaltracker.com/story/show/174235339)
Signed-off-by: Kai Xiang <kxiang@pivotal.io>
This change adds …
> Add ApplicationDataBackupRestore cli plugin for Tanzu MySQL service

- repo-index.yml
Conduit allows a user to connect to a backing store via an ssh tunnel.
This involves pushing an app, binding the service to it, and then creating an ssh tunnel.
Users can now customise the service binding using `-c` to match `cf bind-service`
We are shipping a new feature wherein users can create read-only service bindings. We would like users to be able to do this via conduit.
This version bump enables our users to use a new feature
Anyone who uses `cf conduit`
> conduit: update to version 12

- repo-index.yml
Signed-off-by: Jacob Schuenke <jschuenke@pivotal.io>
We've updated the log-meta --noise command to use metadata rather than actually counting envelopes to make it more reliable and performant.
It improves the usability for users with large foundations.
N/A
Yes, there are several users that require this change to properly test their foundations.
Who else is affected by the change?
No one.
> bump log-cache-cli

- repo-index.yml
https://github.com/cloudfoundry/log-cache-cli/releases/tag/v4.0.0
> bump log cache

- repo-index.yml
This is the initial launch of the restage all plugin. This allows for all applications (with filters) to be restaged within a …
> Initial Release - CF Restage All

- repo-index.yml
> Update MysqlTools version to 0.9.0

- repo-index.yml
Authored-by: Shaan Sapra <shsapra@vmware.com>
There is a new flag argument to control how many backups are listed.
`cf adbr …
> Update ApplicationDataBackupRestore cli plugin version to 0.3.0

- repo-index.yml
Updated alias to be cspush instead of csp, which cf7 now takes for create-space.  While cspush shall be default, there is …
> Bump the Create-Service-Push plugin version to 1.3.2

- repo-index.yml
Makes Conduit 0.0.13 available
Conduit is used widely by [GOV.UK PaaS](https://cloud.service.gov.uk/) tenants, and version 0.0.13 makes it possible to connect to InfluxDB services
Not super urgent. Conduit has been stable for a long while, and this is a relatively minor change.
Anybody else who has picked up Conduit
> Update Conduit plugin to v0.0.13

- repo-index.yml
bump log-cache plugin to 4.0.3. This update bumps golang to 1.17
go 1.16 is going out of support, so we need to bump to 1.17
N/A
Not very urgent
@ctlong
> Bump log-cache-cli to 4.0.3

- repo-index.yml
Bump metric-registrar plugin to 1.3.4. This update bumps golang to 1.17.
Golang 1.16 is going out of support, so we wanted to get ahead of that.
None
Not very urgent
@rroberts2222
> Update metric-registrar plugin to 1.3.4

- repo-index.yml
Make the log-cache cf CLI plugin v4.0.4 available, which bumps dependencies for stability and is compiled with go1.18.
Bumping to go1.18 ahead of the go1.17 EOGS ~August.
N/A
Not very urgent.
N/A
> Bump log-cache plugin to v4.0.4

- repo-index.yml
Update help text to accurately reflect command
Previously help was showing `cf adbr status` but the "real" command is `cf adbr …
> Update ApplicationDataBackupRestore cli plugin version to 0.4.0

- repo-index.yml
This PR will delete cf-security-entitlement plugin because this version is depreciated and we won't update anymore.
So to avoid the use of an old version we would like to delete it. 
Thanks.
> Delete depreciated cf security plugin

- repo-index.yml
- Built with Go 1.19.3
- Bumps Go to 1.19.3.
> Bump log-cache-cli plugin to v4.0.9

- repo-index.yml
* update golang for the two plugins we manage
* include a major improvement to functionality to the log-cache plugin. Users can now use the --json flag on tail and be able to actually read their logs. 
new golang versions
> update cli plugins

- repo-index.yml
Bumps the plugin to go1.20.4.
None.
Non-urgent.
None.
> Bump log-cache to v5.0.1

- repo-index.yml
Bumps the plugin to go1.20.4.
None.
Non-urgent.
None.
> Bump metric-registrar-cli to 1.3.10

- repo-index.yml
Bump log-cache to 5.0.3
Regular security patch
None
Not that urgent
@rroberts2222
> Bump log-cache to 5.0.3

- repo-index.yml
Bump metric-registrar-cli to 1.3.12
Regular security patch
> Bump metric-registrar-cli to 1.3.12

- repo-index.yml
Bump metric-registrar to v1.4.3
Keep metric-registrar up-to-date.
None
Not that urgent
None
> Bump metric-registrar to v1.4.3

- repo-index.yml
Bump log-cache plugin to v5.0.5
Get latest version of the log-cache plugin
None
Not that urgent
None
> Bump log-cache to v5.0.5

- repo-index.yml
Not adding a new plugin.
Removes the [cf-drain-cli plugin](https://github.com/cloudfoundry/cf-drain-cli), which is deprecated. The repo is archived, and has advertised removal for some time.
Removes deprecated plugin from the community list, which should theoretically contain supported, recommended plugins.
None
Not that urgent
Anyone still using this plugin. They should stop using it though.
> chore: Remove deprecated cf-drain-cli

- ui/index.html
Use latest GA tag to use Google Analytics 4.
What benefits will be realized by the code change? What users would want this …
> Change tag to use Google Analytics 4

- repo-index.yml
Upgrade plugin to use CloudFoundry v3 API instead of v2
SAP has deprecated use of Cloud Foundry v2 API in SAP BTP Cloud Foundry …
> Update html5-plugin to 1.4.7

- repo-index.yml
The last update of these two plugins left out the version field. Adding a fix so that the versions now match.
The last update of …
> Fix mismatched versions of log-cache and metric-registrar

- repo-index.yml
Patch update to the log-cache cf CLI plugin. It's had some dependencies bumped and is built with a new version of Go.
Updates the log-cache cf CLI plugin to latest.
None
Slightly less than urgent.
None
> Bump log-cache to v5.0.7

- repo-index.yml
Some dependency bumps, a fix related to `cf tail` JSON output, and a (breaking change) removal of certain env vars that we believe to no longer be needed / in use.
Updates the log-cache cf CLI plugin to latest.
None.
Slightly less than urgent.
None.
> Bump log-cache to v6.0.0

- repo-index.yml
The [saphanaacademy/defaultenv](https://github.com/saphanaacademy/defaultenv) repository is no longer active, as the SAP Hana Academy was closed at the end of last year. Tom and I have taken over the development and the repository now lives in the `sap`-organization.
> Update DefaultEnv to 1.1.0

- repo-index.yml
Fast follow-up to the adbr/0.6.0 bump yesterday to fix a compilation issue that could cause problems when running the linux plugins on older environments.
> Update ApplicationDataBackupRestore cli plugin version to 0.7.0

- repo-index.yml
Bumps the cf java plugin to 3.0.2. This new version fixes compatibility issues for Windows users.
> Update version of cf java plugin

- repo-index.yml
This PR bumps the DefaultEnv plugin to v1.1.1. This version improves compatibility by disabling CGO in the build process.
> chore: bump DefaultEnv to 1.1.1

- repo-index.yml
Includes fix for container selection of heap dump source.
> Bump cf java plugin version to version 3.0.3

- repo-index.yml
Sorry for the follow-up of #484.
While I did update the checksums, I forgot to update the download URL.
> Fix outdated download URL of java plugin

- repo-index.yml
Add the stack auditor, a plugin that helps operators know which stacks are in use on the platform, to the cli plugin registry
> Add the stack auditor, a plugin that helps operators know which stacks are in use on the platform, to the cli plugin

- repo-index.yml
This new build of the `app-autoscaler-plugin` resolves issues when
connecting to foundations running on FIPS-enabled stemcells.
> Bump app-autoscaler-plugin to 3.0.1

- README.md
One of the links to Wikipedia about ISO 8601 needed to be fixed.  There were case differences.    This PR makes the URL portion sharable between the two references.
> Fix wiki link in README.md

- repo-index.yml
It seems that my previous PR had an inadvertently added space in the URL breaking the automation. 
Sorted with `go run sort/main.go repo-index.yml`
Sorry!
This new build of the `app-autoscaler-plugin` resolves issues when
connecting to foundations running on FIPS-enabled stemcells.
> Bump app-autoscaler-plugin to 3.0.1 - second try

- repo-index.yml
This is an automated commit to bump app-autoscaler-cli-plugin to [v4.0.1](https://github.com/cloudfoundry/app-autoscaler-cli-plugin/releases/tag/v4.0.1).
This release moves the plugin from using the Cloud Foundry API v2 to v3. 🎉
It also removes some commands that were not supported by app-autoscaler-release since [v13](https://github.com/cloudfoundry/app-autoscaler-release/releases/tag/v13.0.0), which is why it gets a new major version.
> Bump app-autoscaler-cli-plugin to v4.0.1

- repo-index.yml
This is a Cloud Foundry CLI plugin to quickly identify applications, a given route is pointing to.
Note this will only show applications in organizations and spaces, that the logged-in user has permissions to view.
The plugin also supports targeting to the organization and space of the applications, a given route is pointing to.
```
$ cf lookup-route <my.example.com>
Bound to:
Organization: <org> (<org_guid>)
Space       : <space> (<space_guid>)
App         : <app1> (<app_guid_1>)
App         : <app2> (<app_guid_2>)
```
* There are multiple scenarios, where users wish to quickly search for all the apps bound to a certain route, target the corresponding org and space of the apps to perform some changes there (e.g. list or add users).
* This plugin uses CF API v3. 
TO DOs
> Cloud Foundry Route Lookup Plugin

- repo-index.yml
Updated the conduit plugin to v0.1.2, which contains updates for go libraries used by the conduit plugin. Release notes are …
> Update conduit to v0.1.2

- repo-index.yml
This is an automated commit to bump app-autoscaler-cli-plugin to [v4.1.0](https://github.com/cloudfoundry/app-autoscaler-cli-plugin/releases/tag/v4.1.0)
Changes:
- feat(autoscaling-policy): Displays the Configuration Information [#139](https://github.com/cloudfoundry/app-autoscaler-cli-plugin/pull/139)
> Bump app-autoscaler-cli-plugin to v4.1.0

- repo-index.yml
Bump metric-registar to v1.4.8
Bumps metric-registar to v1.4.8
None
Slightly less than urgent.
Consumers of the metric-registrar …
> Bump metric-registrar to 1.4.8

- repo-index.yml
Bump log-cache plugin to v6.2.1.
Bumps log-cache plugin to v6.2.1.
None
Slightly less than urgent.
None.
> chore: Bump log-cache plugin from v6.0.1 to v6.2.1

- repo-index.yml
This bumps stack-auditor to the latest version, which contains a fix for `cf audit-stack -v`
> Bump stack-auditor to v0.1.5

- repo-index.yml
This is an automated commit to bump app-autoscaler-cli-plugin to [v4.1.1](https://github.com/cloudfoundry/app-autoscaler-cli-plugin/releases/tag/v4.1.1).
> Bump app-autoscaler-cli-plugin to v4.1.1

- repo-index.yml
Description of the Change
Release MultiApps CF CLI Plugin v3.7.0.
This PR updates the plugin version in repo-index.yml and provides the corresponding checksums to make the new release available through the CF CLI Plugin Repository.
Why Is This PR Valuable?
Users will be able to download and use the latest v3.7.0 version of the MultiApps plugin via the plugin repository. Keeping the repository up-to-date ensures that users benefit from the latest features, fixes, and improvements.
Release Highlights (v3.7.0)
•	Improved error messages for cf deploy to display the specific unknown flag when a flag is misspelled.
•	Added User-Agent header to the MultiApps CLI plugin for end-to-end tracing and insights into plugin usage and customer workflows.
Applicable Issues
N/A
How Urgent Is The Change? …
> Update version of multiapps plugin to 3.7.0

- repo-index.yml
Update to existing plugin
Release details: https://github.com/cloudfoundry/upgrade-all-services-cli-plugin/releases/tag/v1.6.0
> Update UpgradeAllServices plugin to v1.6.0

- repo-index.yml
Fix the `thread-dump` command for some Java buildpacks (`sap_java_buildpack_jakarta`) that don't include an SAPJVM.
It fixes a bug that prevents obtaining thread dumps
It fixes one of the core functions of the plugin, so it's pretty urgent.
> Updata java plugin
