repo-index.yml
did it? because that would be wonderful if it did.
=> checking to see if this works

repo-index.yml
Two plugins;
D3 Live Stats :- https://github.com/danhigham/cf-live-stats
Console :- https://github.com/danhigham/cf-console
=> Added cf-console and cf-live-stats

repo-index.yml
=> add autopilot to repository

repo-index.yml
kibana-me-logs plugin release ~~v0.1.0~~ ~~v0.2.0~~ v0.2.1
=> add kibana-me-logs v0.2.1

repo-index.yml
Hi! I'd like to add the scaleover plugin we wrote to the repo. 
Thanks!
=> Add scaleover plugin

repo-index.yml
Signed-off-by: Fabio Berchtold <fabio.berchtold@swisscom.com>
=> add cf-statistics-plugin

repo-index.yml
Hi, I'm Jeanie Jung. I created this plugin and would like to have it published.
=> Added wildcard_plugin

repo-index.yml
[#101789464]
Signed-off-by: James Myers <jmyers@pivotal.io>
=> Update Diego-SSH Plugin to 0.2.1

repo-index.yml
Blue-green deploy plugin described here:
https://github.com/bluemixgaragelondon/cf-blue-green-deploy
=> Add blue-green-deploy plugin

repo-index.yml
manifest-generator plugin described here:
https://github.com/ArthurHlt/plugin-cf-manifest-generator
=> Add manifest-generator plugin

repo-index.yml
* fix where no problem was found, no msg given
* add triage for services
* minor ui changes
Thanks!
=> update doctor plugin

repo-index.yml
* Show total number of apps vs running ones in numbers.
* Add flag "--all-spaces" so that the user can triage all available spaces under the current targeted org.
=> doctor update 1.0.2

repo-index.yml
I would like to share [fastpush](https://github.com/xiwenc/fastpush) with the community.  All related components are opensource.
=> plugins: add fastpush

repo-index.yml
=> Put homepage back for usage report.

repo-index.yml
[#116111421]
Signed-off-by: Corbin Halliwill <challiwill@pivotal.io>
=> Upgrade diego-enabler to v1.1.0

repo-index.yml
- Adds app-nozzle support to see all logs and metrics for the specified app.
=> Updates the version of firehose plugin

repo-index.yml
- This is to support the "MemoryBytesQuota" and "DiskBytesQuota" fields for ContainerMetrics.
[#127599433]
=> Builds plugin with latest dropsonde-protocol definitions

repo-index.yml
Project: https://github.com/mevansam
CI: https://app.wercker.com/mevansam/cf-copy-plugin
=> Added plugin "copy".

repo-index.yml
This version fixes 2 issues with the plugin:
https://github.com/emirozer/cf-doctor-plugin/issues/6
https://github.com/emirozer/cf-doctor-plugin/issues/7
Thanks!
=> doctor update 1.0.3

repo-index.yml
=> updated get-events plugin

repo-index.yml
Closes https://github.com/18F/cf-route-lookup/issues/1.
https://github.com/18F/cf-route-lookup
=> add route-lookup plugin

README.md
Was just a typo. (The rest is my editor automatically removing whitespace.)
=> fix OSX compilation command

repo-index.yml
Also, update references to my name for other plugins to match other ECS Team members.
=> Update do-all plugin

repo-index.yml
Fix the updated time on the `do-all` plugin per suggestion from @dkoper
=> Set updated time

repo-index.yml
Do you mind if I setup a pipeline to update my plugin version automatically?
I'm cutting releases every day right now.
=> Add cflocal 0.8.0

repo-index.yml
=> cf-icd-plugin version 0.0.11

repo-index.yml
As requested by @dkoper here https://github.com/cloudfoundry/cli/issues/1063
=> Adding whoami plugin

ui/index.html
Pull request to add the google analytics code back in.
=> adding google analytics code.

repo-index.yml
CF Login tool to switch between CF environments with a single command.
=> Add cf-aklogin

repo-index.yml
=> Update cf-aklogin to 1.2.9

repo-index.yml
Update fastpush to latest release
=> New release fastpush 1.1.0

repo-index.yml
Updated the repo-index.yml to submit for publication of the Create Service Push plugin.
=> Added V1.0.0 of CreateServicePush Plugin to repo-index.yml

repo-index.yml
CF CLI plugin to hit a metrics endpoint across all your app instances
=> Adds AppMetrics plugin

repo-index.yml
Fixes the formatting of the raw output to be better JSON style format.
=> Updates AppMetrics Plugin to v1.0.2

repo-index.yml
This also resets the created timestamp which I mistakenly modified on the last version.
=> add autopilot 0.0.5

repo-index.yml
This doesn't change any behavior but makes the versions consistent.
=> add autopilot 0.0.6

repo-index.yml
I'd like to add my recycle plugin to the community list
=> Adding cf-recycle-plugin to repo

repo-index.yml
[#156435977]
Signed-off-by: Peter Stone <pstone@pivotal.io>
=> Add CF Drain CLI to the repository

repo-index.yml
=> add noisy neighbor nozzle plugin

repo-index.yml
The create-service-push plugin has been updated
=> Update of repo-index.yml entries for Create-Service-Push 1.1.1

repo-index.yml
[#156029555]
Signed-off-by: Ian Delahorne <idelahorne@pivotal.io>
=> Add mysql-tools plugin to the repository

repo-index.yml
Added latest release of CF Dev v.0.0.6
=> Added CFDev v0.0.6

repo-index.yml
[#158277515]
Signed-off-by: Kai Xiang <kxiang@pivotal.io>
=> Release MysqlTools v0.3.0 cf cli plugin

repo-index.yml
https://github.com/fitzoh/maven-push-plugin
=> Add maven-push plugin

repo-index.yml
=> Update drains plugin to v1.0.0

repo-index.yml
=> Release MysqlTools v0.5.0 cf cli plugin

repo-index.yml
New asset that is compatible with macOS 10.14
=> Add CLI Recorder latest OSX asset

repo-index.yml
Signed-off-by: Andrew Poydence <apoydence@pivotal.io>
=> Update drains to version 1.2.0

repo-index.yml
=> Release MysqlTools v0.6.0 cf cli plugin

repo-index.yml
=> Update metric-registrar to 1.1.0

repo-index.yml
Signed-off-by: Todd Persen <tpersen@pivotal.io>
=> Update log-cache-cli v1.3.0 -> v2.0.0

repo-index.yml
cfdev plugin release from 0.0.12 to 0.0.13
=> Corrected the formatting error on line 402 of repo-index.yml

repo-index.yml
=> Update log-cache-cli v2.0.0 -> v2.1.0

repo-index.yml
Add new autopilot cli-plugin
Plugin will be active maintained
=> add new autopilot cli-plugin application

repo-index.yml
Signed-off-by: Travis Patterson <tpatterson@pivotal.io>
=> add log-stream plugin

repo-index.yml
Update the plugin ci list with new version of autopilot
=> update autopilot version to 0.0.10

repo-index.yml
=> Update MysqlTools version to 0.7.1

repo-index.yml
Update version of `html5-plugin` to v1.2.0, URLs to binaries and checksums
=> update html5-plugin to 1.2.0

repo-index.yml
Update cf-puppeteer version to 0.0.13
- Add new hashes
- Add official homepage with documentation
=> [UPDATE] update cf-puppeteer version to 0.0.13

repo-index.yml
Hello! This is a CF CLI plugin to use the weighted routing feature for the Istio routing tier, developed by the CF Networking Team. 
https://github.com/tstannard/set-weights-plugin
Thanks!
CF Networking Program
[#164789272]
=> add set-weights plugin

repo-index.yml
this pull request updates the multiapps plugin to the newly released version 2.1.1
=> update multiapps plugin to v2.1.1

repo-index.yml
[#166332950]
Signed-off-by: Caitlyn Yu <cyu@pivotal.io>
=> Update Log Stream Plugin to 0.4.0

repo-index.yml
Hi all,
i updated the cf-puppeteer plugin to the final 1.0.0 release
Kind regards
=> Update cf-puppeteer release version

repo-index.yml
=> add cf-security-entitlement plugin

repo-index.yml
Update CF-Puppeteer to new Version 1.1.1
=> [UPDATE] update cf-puppeteer to 1.1.1

repo-index.yml
Adding SSO feature to the aklogin plugin, making it closer aligned with the current `login` default command.
What benefits will …
=> Update aklogin plugin version

repo-index.yml
=> Update top plugin with read-only admin

repo-index.yml
Hi all,
is't just a small update of the plugin.
New Version is:
CF-Puppeteer Version 1.1.3
Kind regards
=> [UPDATE] CF-Puppeteer version 1.1.2

repo-index.yml
=> Introduce ListServices Plugin

repo-index.yml
=> Added SCDF for PCF CLI plugin version 1.0.2 update.

repo-index.yml
This commit updated the version of Conduit to the latest release where
we have improved the communication between the local machine and the
remote backing store by changing the communication libraries in use to
being the go native CF rather than using http libraries.
If you haven't yet, please review our contributing guidelines: …
=> Update Conduit version

repo-index.yml
Updating the `cflocal` plugins in from `0.19.0` to `0.20.0` in conjunction with @sclevine
=> Update cflocal plugins

repo-index.yml
We are releasing a new version of mysql tools, story https://www.pivotaltracker.com/story/show/171960775
=> Update MysqlTools version to 0.8.0

repo-index.yml
You can use a sample Yalm file from https://github.com/enric11/cf-cli-check-before-deploy/blob/master/mta.yaml
To run the script you can use the command "cf check-before-deploy -file. …
=> Plugin Check-before-deploy v.1.0.0

repo-index.yml
Signed-off-by: Enric Castella <e_castella@hotmail.com>
You can use a sample Yalm file from https://github.com/enric11/cf-cli-check-before-deploy/blob/master/mta.yaml
To run the script you …
=> Plugin Check-Before-Deploy new release 1.1.0

repo-index.yml, repo_index_test.go
=> add CF CLI plugin for VMware Tanzu GemFire

repo-index.yml
=> Gemfire Plugin: use gemfire 1.0.6

repo-index.yml
=> correct spelling for gemfire plugin

repo-index.yml
Hi all,
I just bring a new bug fix release for the plugin.
- Fix route mapping.
- Fix push application with vars file.
To get more informations about the Change please see the new Blog [post](https://cf-puppeteer.happytobi.com/posts/release_1.2.1/)
The fix enable some new features introduced in the version 1.2.0.
So it would be nice that all the people can use the new version as soon as possible.
Kind regards
Tobi
=> UPDATE cf-puppeteer version

repo-index.yml
Hi all,
just a new bugfix release.
Kind regards
=> UPDATE cf-puppeteer to version 1.2.2

repo-index.yml
Maintenance update of the plugin.
The currently released plugin is out of date.
https://github.com/cloudfoundry-incubator/cfdev/issues/132
https://github.com/pivotal-cf/pcfdev/issues/393
Not Urgent
None
=> Bump cfdev to 0.0.18

repo-index.yml
Description of the Change:
Updating version of plugin to newest release
=> Update version of multiapps plugin to 2.5.0

repo-index.yml
#Submitting Plugins
I have reviewed our contributing guidelines:  
These requirements are being met:
Please consider my submission and let me know if I need to provide any additions and/or corrections.
-Andrew
andrew.lunde@sap.com
=> Submitting ServiceManagement plugin

repo-index.yml
Description of the Change:
Updating the version of the plugin to the newest release
=> Adopt multiapps-cli-plugin 2.5.1

repo-index.yml
Bumping metric-registrar plugin to v1.3.1.
Thanks!
=> Bump metric-registrar plugin to v1.3.1

repo-index.yml
Bumping log-cache-cli plugin to v4.0.2
Thanks!
=> Bump log-cache plugin to v4.0.2

repo-index.yml
=> Update version of multiapps plugin to 2.6.0

repo-index.yml
Bump cf-security-entitlement plugin to v1.0.1
thanks
=> Bump cf-security-entitlement plugin to v1.0.1

repo-index.yml
This is a minor update that allows to leverage additional configuration option in multiple commands provided by the plugin (with …
=> Update html5-plugin to 1.4.6

repo-index.yml
Various bug fixes
Moderate
-Andrew
=> ServiceManager v1.2.4 plugin update

README.md
=> Add uptime.com badge to the README

repo-index.yml
=> Metric registrar 1.3.3

repo-index.yml
=> Update Java Plugin to 3.0.1

repo-index.yml
Adopt 2.7.0 version of multiapps plugin for CF.
=> Adopt multiapps 2.7.0

repo-index.yml
Including login control
You can use a sample Yalm file from https://github.com/enric11/cf-cli-check-before-deploy/blob/master/mta.yaml
To run the script you can use the command "cf …
=> Check-before-deploy new version 1.2.0

repo-index.yml
We allow our users to create a Let's Encrypt certificate with RSA or ECDSA keys.
Users will benefit from using smaller, faster and more secure ECDSA certificates.
Without this new release, they have to always use RSA.
N.A.
It's not very urgent.
Nobody else is affected.
=> Update Swisscom Application Cloud plugin to v0.2.0

repo-index.yml
Fixed regressions caused by external API changes.
Users will be able to use all commands.
N.A.
It's not very urgent.
Nobody else is affected.
=> Update Swisscom Application Cloud plugin to v0.2.2

repo-index.yml
Adding DefaultEnv plugin for a teammate(Philip Mugglestone).
description: Create default-env.json file with environment variables of an app.
homepage: https://github.com/saphanaacademy/DefaultEnv
-Andrew
=> Added DefaultEnv

repo-index.yml
- update two plugins to have latest versions/go 1.18.1
golang bumps
=> update two plugins with golang 1.18.1

repo-index.yml
This PR updates the Conduit plugin to version 0.0.14 which now includes ARM binaries
Minor change is to include contact details and homepage
With the increasing use of M1 silicon we need to release an appropriate binary for use on the ARM architecture
None
Not urgent
Who else is affected by the change?
=> Update conduit plugin to 0.0.14

.github/workflows/test.yml
Currently one of the pain points of reviewing
and approving plugins PR is the fact that there's
a possibility that authors forgot to run
the sort command before publishing the PR.
=> Adds testing to cli-plugins-repo PRs

repo-index.yml
=> Update version of multiapps plugin to 3.0.1

repo-index.yml
=> Fix multiapps checksums

repo-index.yml
Simple bump of conduit plugin
Adds new features to conduit plugin
=> Bump conduit plugin to v0.1.0

repo-index.yml
[#186034123](https://www.pivotaltracker.com/story/show/186034123)
We must be able to understand the design of your change from …
=> Update MysqlTools version to 0.10.0

repo-index.yml
Bump spring-cloud-services plugin to v1.0.23
=> Bump spring-cloud-services plugin to v1.0.23

repo-index.yml
Bump spring-cloud-services plugin to v1.0.23
=> Bump spring-cloud-services plugin to v1.0.24

repo-index.yml
=> Bump mysql-plugin to v2.1.0

repo-index.yml
=> Update version of spring-cloud-services in repo-index.yml to match download urls

repo-index.yml
Bump conduit plugin to a version that knows its own version.
Having a plugin that reports a different version from what is downloaded is confusing.
#429
It's not.
=> Bump conduit plugin to v0.1.1

repo-index.yml
=> Updated to CF API v3

repo-index.yml
* [ x] The plugin's `name` field in `repo-index.yml` matches the `Name` field in the plugin's `plugin.PluginMetadata` section
* [x ] The plugin's `url` field in `repo-index.yml` contains …
=> Release MySQL ADBR plugin v0.5.0

repo-index.yml
Bump spring-cloud-services plugin to v1.0.25
=> Bump spring-cloud-services plugin to v1.0.25

repo-index.yml
=> Update MysqlTools version to 0.10.1

repo-index.yml
The plugin now asks for confirmations during a restore operation, as well as dependency bumps and updating the plugin homepage …
=> Update ApplicationDataBackupRestore cli plugin version to 0.6.0

repo-index.yml
Bump spring-cloud-services plugin to v1.0.26
=> Bump spring-cloud-services plugin to v1.0.26

repo-index.yml
Bump service-instance-logs plugin to v1.0.4
=> Bump service-instance-logs plugin to v1.0.4

repo-index.yml
not sure while the [pr pipeline ](https://github.com/cloudfoundry/cli-plugin-repo/pull/482)didn't catch this issue 🤷 
also confusing that the pipeline says that it isn't sorted cause that's not the issue (yay whitespace)
In particular ensure the …
=> run 'go run sort/main.go repo-index.yml' to fix issue

repo-index.yml
Reverts cloudfoundry/cli-plugin-repo#488
=> Revert "Bump app-autoscaler-plugin to 3.0.1"

.github/workflows/test.yml
Enable test workflow to run as PR check
=> Add Test workflow to PR

repo-index.yml
Allow customer to download newest version of ADBR CLI, with new features for supporting incremental backups and point-in-time …
=> Update ApplicationDataBackupRestore cli plugin version to 0.8.0
